# Generated by Django 3.2.3 on 2021-06-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventtype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='your_number',
            field=models.CharField(max_length=20),
        ),
    ]
