# Generated by Django 3.2.3 on 2021-06-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210617_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventtype'),
        ),
    ]
