# Generated by Django 3.2.3 on 2021-06-25 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[A-Za-z]*$', 'Only letters are allowed.', 'Invalid Name')]),
        ),
    ]
