# Generated by Django 3.2.3 on 2021-06-25 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_cust_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county_area',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
