# Generated by Django 3.2.3 on 2021-06-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0004_bundle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlecategory',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
