# Generated by Django 3.2.3 on 2021-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0005_bundlecategory_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
