# Generated by Django 3.2.3 on 2021-06-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_message', models.CharField(max_length=40)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prints', to='products.product')),
            ],
        ),
    ]
