# Generated by Django 3.2.3 on 2021-06-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20210616_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrintedProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('custom_message', models.CharField(max_length=40)),
            ],
            bases=('products.product',),
        ),
    ]
