# Generated by Django 3.2.3 on 2021-06-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0006_bundle_custom'),
        ('checkout', '0003_alter_orderitem_product'),
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPrintedProduct',
        ),
    ]
