# Generated by Django 3.2.3 on 2021-06-16 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20210616_1042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printing', '0002_delete_customprintedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrintedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_message', models.CharField(max_length=40)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prints', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
