# Generated by Django 3.2.3 on 2021-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_customprintedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprintedproduct',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
