# Generated by Django 3.2.3 on 2021-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle_product',
            field=models.BooleanField(default=False),
        ),
    ]
