# Generated by Django 3.2.3 on 2021-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210528_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='display_name',
            new_name='color',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
