# Generated by Django 3.2.3 on 2021-06-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210616_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_held',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_bag',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
