# Generated by Django 3.2.3 on 2021-05-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210530_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='message_editable',
            field=models.BooleanField(default=False),
        ),
    ]
