# Generated by Django 3.2.3 on 2021-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_message_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_in_bag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
