# Generated by Django 3.2.3 on 2021-06-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_bundle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundleitem',
            old_name='value',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='key',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bundle_items',
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.bundleitem'),
        ),
    ]
