# Generated by Django 3.2.3 on 2021-06-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210607_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleitem',
            name='product_name',
            field=models.CharField(default='n/a', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='product_id',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='bundle_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bundleitem'),
        ),
    ]
