# Generated by Django 3.2.3 on 2021-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210607_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundle_items',
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_items',
            field=models.ManyToManyField(blank=True, null=True, to='products.BundleItem'),
        ),
    ]
