# Generated by Django 3.2.3 on 2021-06-07 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210607_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundleitem',
            old_name='product_id',
            new_name='bundle_item_id',
        ),
        migrations.RenameField(
            model_name='bundleitem',
            old_name='product_name',
            new_name='bundle_item_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bundle_items',
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product'),
        ),
    ]
