# Generated by Django 3.2.3 on 2021-06-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210607_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='name',
            field=models.CharField(default='n/a', max_length=254),
            preserve_default=False,
        ),
    ]
