# Generated by Django 3.2.3 on 2021-06-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_bundle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundleitem',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
        migrations.DeleteModel(
            name='BundleItem',
        ),
    ]
