# Generated by Django 3.2.3 on 2021-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210607_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_items',
            field=models.ManyToManyField(blank=True, related_name='_products_product_bundle_items_+', to='products.Product'),
        ),
    ]
