# Generated by Django 3.2.3 on 2021-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_bundle_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bundle_items',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
