# Generated by Django 3.2.3 on 2021-06-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210608_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product'),
        ),
    ]
