# Generated by Django 3.2.3 on 2021-06-08 19:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_bundleitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.CharField(editable=False, max_length=254)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.RenameField(
            model_name='bundleitem',
            old_name='cost',
            new_name='item_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bundle',
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.bundle'),
            preserve_default=False,
        ),
    ]
