# Generated by Django 3.2.3 on 2021-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210608_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
